name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
        env:
          TEXINPUTS: ".:"
      - name: Commit the generated resume pdf back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply the new changes
          file_pattern: *.pdf
